### PR TITLE
Updated Anilist Mapping

### PR DESCRIPTION
**Pull request by handy1928**
Changed Anilist mapped to some Fields.

Description - stripped HTML elements and remove Source text.
Title - set English and Romaji to Series and LocalizedSeries
Count - add number of Volumes to Count
People - Changed and added a few mappings, Writes multiple People in fields (Comma seperated) if present

### CODE REVIEW

**Comment by ThePromidius** [comment]
You propose some interesting changes. I'll keep the PR alive until i add settings for sources. (its already started).
Thanks for your contribution

**Comment by majora2007** [comment]
I def like the Description and Count changes. I think if done, Series and Localized Series might need a button to quickly swap them or a setting on how certain things should be written. Same with People. Some mappings in settings might be super helpful for where the different fields map to.

**Comment by majora2007** [comment]
Just a heads up, I'm currently reworking how External Metadata Providers can load custom settings for the user to tweak in #130. I think it would be advisable to hold on this PR and get mine in first, then refactor to use the new mechanisms. This will give the user complete control on how fields from external sources are mapped to the ComicInfo.

**Comment by majora2007** [comment]
After #139 is merged, you can reopen your PR and we can get it in. You will be able to add settings to allow the user to choose if they want English or Romanji as the Series or LocalizedSeries.

**Pull request closed without merging**
