### PR TITLE
use original compression type instead of forcing store

### PR DESCRIPTION
**Pull request by 1024mb**

### CODE REVIEW

**Comment by ThePromidius** [comment]
You only changed the compression type when appending comicinfo. 
Shouldn't this also be changed when the .cbz is originally recreated? (when there's the need to recompress)

**Comment by 1024mb** [comment]
Done, also added checking for directories or zero files as those aren't compressed and we will get the wrong type if they are the first item inside the zip file.

**Comment by ThePromidius** [comment]
I've just now realized this PR affects current master branch.
This is no longer being updated because we are now fully working on the rework and there's no more updates planned to this now "legacy" version.

Check `rework/master`

**Comment by ThePromidius** [comment]
Feel free to review the rework branch and raise a new PR

**Pull request closed without merging**
